create table if not exists public.danmaku_messages (
  id bigint generated by default as identity primary key,
  content text not null check (char_length(content) > 0 and char_length(content) <= 100),
  emoji text,
  user_id text not null,
  user_name text not null,
  created_at timestamptz not null default now()
);

alter table public.danmaku_messages enable row level security;

drop policy if exists "danmaku_select_all" on public.danmaku_messages;
create policy "danmaku_select_all"
on public.danmaku_messages
for select
to anon, authenticated
using (true);

drop policy if exists "danmaku_insert_all" on public.danmaku_messages;
create policy "danmaku_insert_all"
on public.danmaku_messages
for insert
to anon, authenticated
with check (true);
